### ISSUE TITLE
Probleme seit letztem Update von Alpha ESS

### ISSUE THREAD

**Issue by StefanRdacia** [Aboreon/Homey-AlphaESS-inverter#2]
Seit letztem Wocheende bekomme ich keine Daten mehr übertragen 
Alpha ESS hat ihr System geupdatet

**Comment by Aboreon** [comment]
I noticed it too. They changed something and I'm unsure what causes this. I'll try to find some time to look into it.

**Comment by StefanRdacia** [comment]
Seit heute geht es wieder

**Comment by Aboreon** [comment]
I noticed it too. They changed something and I'm unsure what causes this. I'll try to find some time to look into it.

**Comment by Aboreon** [comment]
Dear AlphaESS user,

 

Last Saturday, October 12, 2024, a system upgrade was announced by AlphaESS. Last Monday, October 14, we informed most of you, apologies to those who did not receive the first email, that this process had been delayed.

 

The upgrade involved an extensive continental server migration with the aim of making the AlphaESS cloud environment more robust and scalable.

 

What we see today is that all systems have largely been restored, but we still see hick ups (control on / control off) in systems that are controlled by external VPP platforms. Such as Frank Energie and SEMS. This is of course very annoying. We are working hard behind the scenes to get 100% of the systems up and running in a stable manner.

Hope it remains working and stable now
